const $=id=>document.getElementById(id);let client=null,currentUser=null,mode='login';const skins=[['aurora','Aurora','#86f7df',0],['sol','Solaris','#ffd479',25],['void','Voidglass','#c084fc',50],['rose','Rose Signal','#ff75b6',75],['ember','Ember Warden','#ff6879',100]];
function notice(text,type=''){const e=$('authMessage');if(e){e.textContent=text;e.className=`auth-message ${type}`;}}
function init(){const c=window.__SUPABASE_CONFIG__;if(!c||c.url.includes('YOUR_')){notice('Add your Supabase URL and anon key to config.js before signing in.','error');return;}client=window.supabase.createClient(c.url,c.anonKey);bind();renderShop();if(localStorage.getItem('loom-cookies')!=='yes')$('cookies')?.classList.add('show');client.auth.getSession().then(({data})=>{if(data.session)enter(data.session.user);});}
function bind(){document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{mode=t.dataset.mode;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));$('nameWrap')?.classList.toggle('hidden',mode!=='signup');$('submitAuthBtn').textContent=mode==='signup'?'Create account ↗':'Log in ↗';});$('authForm').onsubmit=auth;$('fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();$('shopButton').onclick=()=>{$('shopModal').classList.remove('hidden');renderShop();};$('settingsButton').onclick=()=>$('settingsModal').classList.remove('hidden');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));$('acceptCookies').onclick=()=>{localStorage.setItem('loom-cookies','yes');$('cookies').classList.remove('show');};$('logoutBtn').onclick=async()=>{await client.auth.signOut();location.reload();};$('reportButton').onclick=()=>$('reportModal').classList.remove('hidden');$('reportForm').onsubmit=report;$('clearSave').onclick=async()=>{if(currentUser){await client.from('player_progress').delete().eq('id',currentUser.id);window.gameAPI.buildLevel(1);notice('Cloud save reset.','success');}};window.addEventListener('loom-win',async()=>{if(currentUser){window.gameAPI.game.level=Math.min(24,window.gameAPI.game.level+1);await save();}window.gameAPI.buildLevel(window.gameAPI.game.level);});window.addEventListener('loom-lost',save);window.addEventListener('beforeunload',save);}
async function auth(e){e.preventDefault();if(!client){notice('Configure Supabase first.','error');return;}const email=$('emailInput').value.trim(),password=$('passwordInput').value;if(mode==='signup'){const r=await client.auth.signUp({email,password,options:{data:{display_name:$('nameInput').value.trim()||email.split('@')[0]}}});notice(r.error?.message||'Check your email to verify your account.',r.error?'error':'success');return;}const r=await client.auth.signInWithPassword({email,password});if(r.error){notice(r.error.message,'error');return;}await enter(r.data.user);}
async function enter(user){currentUser=user;$('authPanel').classList.add('hidden');$('gamePanel').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('userBadge').textContent=(user.email||'PILOT').toUpperCase();const p=await client.from('profiles').select('*').eq('id',user.id).single();if(p.data)$('userBadge').textContent=(p.data.display_name||user.email).toUpperCase();const q=await client.from('player_progress').select('*').eq('id',user.id).single();if(q.data){window.gameAPI.buildLevel(Math.max(1,Math.min(24,q.data.level||1)));window.gameAPI.setSkin?.(q.data.skin||'aurora');}window.gameAPI.start();}
async function save(){if(!client||!currentUser)return;const g=window.gameAPI.game;await client.from('player_progress').upsert({id:currentUser.id,level:g.level,best_score:g.score,health:Math.round(g.health),skin:g.skin||'aurora',last_saved_at:new Date().toISOString()});if($('saveStatus'))$('saveStatus').textContent='cloud saved';}
function renderShop(){const box=$('skinGrid');if(!box)return;box.innerHTML=skins.map(([id,name,color,price])=>`<button class="skin" data-skin="${id}" style="--skin:${color}"><i></i><b>${name}</b><small>${price?price+' light':'Starter skin'}</small></button>`).join('');box.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{window.gameAPI.setSkin?.(b.dataset.skin);localStorage.setItem('loom-skin',b.dataset.skin);box.querySelectorAll('.skin').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');});}
async function report(e){e.preventDefault();if(!currentUser){$('reportMessage').textContent='Sign in first.';return;}const r=await client.from('bug_reports').insert({user_id:currentUser.id,title:$('bugTitle').value,details:$('bugDetails').value,page:location.href});$('reportMessage').textContent=r.error?.message||'Report sent to the owner review queue.';if(!r.error)e.target.reset();}
window.addEventListener('DOMContentLoaded',init);
