const $=id=>document.getElementById(id);let client=null,currentUser=null,mode='login';const skins=[['aurora','Aurora','#86f7df',0],['sol','Solaris','#ffd479',25],['void','Voidglass','#c084fc',50],['ember','Ember','#ff8a65',75]];
function notice(text,type=''){const e=$('authMessage');if(e){e.textContent=text;e.className=`auth-message ${type}`;}}
function init(){const c=window.__SUPABASE_CONFIG__;if(!c||!c.url||!c.anonKey||c.url.includes('YOUR_')||c.anonKey.includes('YOUR_')){notice('Add your Supabase URL and publishable key to config.js before signing in.','error');bind();return;}if(!window.supabase||typeof window.supabase.createClient!=='function'){notice('Supabase failed to load. Check your internet connection and refresh.','error');bind();return;}client=window.supabase.createClient(c.url,c.anonKey);bind();client.auth.getSession().then(({data})=>{if(data.session)enter(data.session.user);});client.auth.onAuthStateChange((event,session)=>{if(session)enter(session.user);});}
function bind(){document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{mode=t.dataset.mode;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));$('nameWrap')?.classList.toggle('hidden',mode!=='signup');$('authSubmit').textContent=mode==='signup'?'Create account ↗':'Log in ↗';notice('');});$('authForm')?.addEventListener('submit',auth);$('logoutBtn')?.addEventListener('click',()=>client?.auth.signOut());$('acceptCookies')?.addEventListener('click',()=>{localStorage.setItem('loomCookies','1');$('cookies').classList.add('hidden');});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close)?.classList.add('hidden'));$('shopButton')?.addEventListener('click',()=>{$('shopModal')?.classList.remove('hidden');renderShop();});$('settingsButton')?.addEventListener('click',()=>$('settingsModal')?.classList.remove('hidden'));$('reportButton')?.addEventListener('click',()=>$('reportModal')?.classList.remove('hidden'));}
async function auth(e){e.preventDefault();if(!client){notice('Configure Supabase first.','error');return;}const email=$('emailInput').value.trim(),password=$('passwordInput').value;if(mode==='signup'){const name=$('nameInput')?.value.trim()||'Pilot';const r=await client.auth.signUp({email,password,options:{data:{pilot_name:name}}});if(r.error){notice(r.error.message,'error');return;}notice(r.data.session?'Account created.':'Account created. Check your email to confirm it.','success');}else{const r=await client.auth.signInWithPassword({email,password});if(r.error){notice(r.error.message,'error');return;}enter(r.data.user);}}
async function enter(user){currentUser=user;$('authPanel')?.classList.add('hidden');$('gamePanel')?.classList.remove('hidden');$('logoutBtn')?.classList.remove('hidden');if($('userBadge'))$('userBadge').textContent=user.user_metadata?.pilot_name||user.email;window.gameAPI?.buildLevel?.(1);}
async function save(){if(!client||!currentUser)return;const g=window.gameAPI?.game;if(!g)return;await client.from('player_progress').upsert({id:currentUser.id,level:g.level,best_score:g.score,health:Math.round(g.health),energy:Math.round(g.energy),skin:g.skin});}
function renderShop(){const box=$('skinGrid');if(!box)return;box.innerHTML=skins.map(([id,name,color,price])=>`<button class="skin" data-skin="${id}" style="--skin:${color}"><i></i><b>${name}</b><small>${price===0?'Free':price+' shards'}</small></button>`).join('');box.querySelectorAll('.skin').forEach(b=>b.onclick=()=>{if(window.gameAPI?.setSkin)window.gameAPI.setSkin(b.dataset.skin);});}
async function report(e){e.preventDefault();if(!currentUser){$('reportMessage').textContent='Sign in first.';return;}const r=await client.from('bug_reports').insert({user_id:currentUser.id,title:$('reportTitle').value,body:$('reportBody').value});$('reportMessage').textContent=r.error?r.error.message:'Transmission received.';}
window.addEventListener('DOMContentLoaded',init);